import { Task, Sprint } from '../types/task';

export const SEED_VERSION = 'v3';

const now = new Date();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString();
const daysAhead = (d: number) => new Date(now.getTime() + d * 86400000).toISOString().slice(0, 10);
const dateStr = (d: number) => new Date(now.getTime() - d * 86400000).toISOString().slice(0, 10);

export const SEED_SPRINTS: Sprint[] = [
  {
    id: 'sprint-1',
    name: 'Sprint 1 – Foundation',
    startDate: dateStr(42),
    endDate: dateStr(28),
    isActive: false,
  },
  {
    id: 'sprint-2',
    name: 'Sprint 2 – Core Features',
    startDate: dateStr(14),
    endDate: daysAhead(0),
    isActive: true,
  },
  {
    id: 'sprint-3',
    name: 'Sprint 3 – Polish & Launch',
    startDate: daysAhead(1),
    endDate: daysAhead(14),
    isActive: false,
  },
];

export const SEED_TASKS: Task[] = [
  // Sprint 1 – all done, one archived
  {
    id: 'task-1',
    title: 'Set up project scaffolding',
    description: 'Initialize repository, configure build tools, set up CI/CD pipeline',
    status: 'done',
    storyPoints: 3,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(35),
    sprintId: 'sprint-1',
    order: 0,
    archivedAt: daysAgo(28),
    inProgressAt: daysAgo(38),
    dueDate: dateStr(35),
  },
  {
    id: 'task-2',
    title: 'Design database schema',
    description: 'Define all tables, relationships, and indexes for the core data model',
    status: 'done',
    storyPoints: 5,
    createdAt: daysAgo(39),
    updatedAt: daysAgo(33),
    sprintId: 'sprint-1',
    order: 1,
    archivedAt: daysAgo(27),
    inProgressAt: daysAgo(37),
  },
  {
    id: 'task-3',
    title: 'Implement authentication',
    description: 'OAuth2 login flow with JWT refresh tokens and session management',
    status: 'done',
    storyPoints: 8,
    createdAt: daysAgo(38),
    updatedAt: daysAgo(30),
    sprintId: 'sprint-1',
    order: 2,
    archivedAt: daysAgo(26),
    inProgressAt: daysAgo(36),
    dueDate: dateStr(30),
  },
  {
    id: 'task-4',
    title: 'Create REST API endpoints',
    description: 'Build CRUD endpoints for tasks, sprints, and user profiles',
    status: 'done',
    storyPoints: 13,
    createdAt: daysAgo(37),
    updatedAt: daysAgo(29),
    sprintId: 'sprint-1',
    order: 3,
    archivedAt: daysAgo(25),
    inProgressAt: daysAgo(34),
  },

  // Sprint 2 – active sprint, mix of states
  {
    id: 'task-5',
    title: 'Build kanban board UI',
    description: 'Drag-and-drop columns with real-time status updates and card reordering',
    status: 'in-progress',
    storyPoints: 8,
    createdAt: daysAgo(13),
    updatedAt: daysAgo(2),
    sprintId: 'sprint-2',
    order: 0,
    inProgressAt: daysAgo(5),
    dueDate: daysAhead(2),
  },
  {
    id: 'task-6',
    title: 'Implement planning poker',
    description: 'Fibonacci voting system for story point estimation with reveal mechanic',
    status: 'in-progress',
    storyPoints: 5,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(1),
    sprintId: 'sprint-2',
    order: 1,
    inProgressAt: daysAgo(3),
  },
  {
    id: 'task-7',
    title: 'Add sprint management',
    description: 'Create, edit, and activate sprints; assign tasks to sprints from backlog',
    status: 'todo',
    storyPoints: 5,
    createdAt: daysAgo(11),
    updatedAt: daysAgo(11),
    sprintId: 'sprint-2',
    order: 2,
    dueDate: daysAhead(5),
  },
  {
    id: 'task-8',
    title: 'Multi-field search and filtering',
    description: 'Search by title, description, status, story points, and dates with operators',
    status: 'todo',
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
    sprintId: 'sprint-2',
    order: 3,
  },
  {
    id: 'task-9',
    title: 'Done folder and trash bin',
    description: 'Archive completed tasks and soft-delete with 30-day retention period',
    status: 'done',
    storyPoints: 3,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(4),
    sprintId: 'sprint-2',
    order: 4,
    inProgressAt: daysAgo(8),
    dueDate: daysAhead(1),
  },
  {
    id: 'task-10',
    title: 'Keyboard shortcuts',
    description: 'Implement / and Cmd-F for search focus, Esc to clear',
    status: 'todo',
    storyPoints: 2,
    createdAt: daysAgo(9),
    updatedAt: daysAgo(9),
    sprintId: 'sprint-2',
    order: 5,
  },

  // Sprint 3 – all todo, future sprint
  {
    id: 'task-11',
    title: 'Mobile responsive design',
    description: 'Optimize all views for tablet and mobile screen sizes',
    status: 'todo',
    storyPoints: 5,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
    sprintId: 'sprint-3',
    order: 0,
    dueDate: daysAhead(10),
  },
  {
    id: 'task-12',
    title: 'Dark mode support',
    description: 'Implement theme switching with system preference detection',
    status: 'todo',
    storyPoints: 3,
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
    sprintId: 'sprint-3',
    order: 1,
  },
  {
    id: 'task-13',
    title: 'Export to CSV',
    description: 'Allow users to export task lists and sprint reports as CSV files',
    status: 'todo',
    storyPoints: 2,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
    sprintId: 'sprint-3',
    order: 2,
    dueDate: daysAhead(12),
  },

  // Backlog tasks (no sprint)
  {
    id: 'task-14',
    title: 'Email notification system',
    description: 'Send digest emails for sprint summaries and overdue task reminders',
    status: 'todo',
    storyPoints: 13,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(20),
    order: 0,
  },
  {
    id: 'task-15',
    title: 'Slack integration',
    description: 'Post notifications to Slack channels when tasks move to done or get assigned',
    status: 'todo',
    createdAt: daysAgo(18),
    updatedAt: daysAgo(18),
    order: 1,
    dueDate: daysAhead(30),
  },
  {
    id: 'task-16',
    title: 'Analytics dashboard',
    description: 'Velocity charts, burndown graphs, and team performance metrics',
    status: 'todo',
    storyPoints: 21,
    createdAt: daysAgo(15),
    updatedAt: daysAgo(15),
    order: 2,
  },

  // Trash items
  {
    id: 'task-17',
    title: 'Old API v1 documentation',
    description: 'Documentation for the deprecated v1 API endpoints – no longer needed',
    status: 'todo',
    createdAt: daysAgo(30),
    updatedAt: daysAgo(5),
    order: 99,
    deletedAt: daysAgo(5),
  },
  {
    id: 'task-18',
    title: 'Duplicate: Setup CI pipeline',
    description: 'This was a duplicate of task-1 and was removed',
    status: 'todo',
    storyPoints: 1,
    createdAt: daysAgo(35),
    updatedAt: daysAgo(29),
    order: 100,
    deletedAt: daysAgo(29),
  },
];
