import { Task, Sprint, KanbanColumn } from '../types/task';

export const SEED_VERSION = 'v4';

const now = new Date();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString();
const daysAhead = (d: number) => new Date(now.getTime() + d * 86400000).toISOString().slice(0, 10);
const dateStr = (d: number) => new Date(now.getTime() - d * 86400000).toISOString().slice(0, 10);

export const SEED_COLUMNS: KanbanColumn[] = [
  { id: 'col-todo', name: 'To Do', order: 0, semanticStatus: 'not-started', color: 'gray' },
  { id: 'col-in-progress', name: 'In Progress', order: 1, semanticStatus: 'in-progress', color: 'blue' },
  { id: 'col-in-review', name: 'In Review', order: 2, semanticStatus: 'in-progress', color: 'purple' },
  { id: 'col-done', name: 'Done', order: 3, semanticStatus: 'done', color: 'green' },
];

export const SEED_SPRINTS: Sprint[] = [
  {
    id: 'sprint-1',
    name: 'Sprint 1 – Foundation',
    startDate: dateStr(42),
    endDate: dateStr(28),
    isActive: false,
  },
  {
    id: 'sprint-2',
    name: 'Sprint 2 – Core Features',
    startDate: dateStr(14),
    endDate: daysAhead(0),
    isActive: true,
  },
  {
    id: 'sprint-3',
    name: 'Sprint 3 – Polish & Launch',
    startDate: daysAhead(1),
    endDate: daysAhead(14),
    isActive: false,
  },
];

export const SEED_TASKS: Task[] = [
  // Sprint 1 – all done, archived
  {
    id: 'task-1',
    title: 'Set up project scaffolding',
    notes: 'Initialize repository, configure build tools, set up CI/CD pipeline',
    columnId: 'col-done',
    storyPoints: 3,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(35),
    sprintId: 'sprint-1',
    order: 0,
    archivedAt: daysAgo(28),
    inProgressAt: daysAgo(38),
    dueDate: dateStr(35),
    tags: ['infrastructure', 'setup'],
  },
  {
    id: 'task-2',
    title: 'Design database schema',
    notes: 'Define all tables, relationships, and indexes for the core data model',
    columnId: 'col-done',
    storyPoints: 5,
    createdAt: daysAgo(39),
    updatedAt: daysAgo(33),
    sprintId: 'sprint-1',
    order: 1,
    archivedAt: daysAgo(27),
    inProgressAt: daysAgo(37),
    tags: ['backend', 'database'],
  },
  {
    id: 'task-3',
    title: 'Implement authentication',
    notes: 'OAuth2 login flow with JWT refresh tokens and session management',
    columnId: 'col-done',
    storyPoints: 8,
    createdAt: daysAgo(38),
    updatedAt: daysAgo(30),
    sprintId: 'sprint-1',
    order: 2,
    archivedAt: daysAgo(26),
    inProgressAt: daysAgo(36),
    dueDate: dateStr(30),
    tags: ['backend', 'security'],
  },
  {
    id: 'task-4',
    title: 'Create REST API endpoints',
    notes: 'Build CRUD endpoints for tasks, sprints, and user profiles',
    columnId: 'col-done',
    storyPoints: 13,
    createdAt: daysAgo(37),
    updatedAt: daysAgo(29),
    sprintId: 'sprint-1',
    order: 3,
    archivedAt: daysAgo(25),
    inProgressAt: daysAgo(34),
    tags: ['backend', 'api'],
    predecessorIds: ['task-2', 'task-3'],
  },

  // Sprint 2 – active sprint
  {
    id: 'task-5',
    title: 'Build kanban board UI',
    notes: 'Drag-and-drop columns with real-time status updates and card reordering',
    columnId: 'col-in-progress',
    storyPoints: 8,
    createdAt: daysAgo(13),
    updatedAt: daysAgo(2),
    sprintId: 'sprint-2',
    order: 0,
    inProgressAt: daysAgo(5),
    dueDate: daysAhead(2),
    tags: ['frontend', 'kanban'],
  },
  {
    id: 'task-5a',
    title: 'Column drag-and-drop',
    notes: 'Implement draggable cards between columns using hello-pangea/dnd',
    columnId: 'col-done',
    storyPoints: 3,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(3),
    sprintId: 'sprint-2',
    order: 0,
    parentId: 'task-5',
    inProgressAt: daysAgo(6),
    archivedAt: undefined,
    tags: ['frontend'],
  },
  {
    id: 'task-5b',
    title: 'Add column management UI',
    notes: 'Settings panel to add, rename, reorder and delete columns',
    columnId: 'col-in-progress',
    storyPoints: 2,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(1),
    sprintId: 'sprint-2',
    order: 1,
    parentId: 'task-5',
    inProgressAt: daysAgo(2),
    tags: ['frontend'],
  },
  {
    id: 'task-6',
    title: 'Implement planning poker',
    notes: 'Fibonacci voting system for story point estimation with reveal mechanic',
    columnId: 'col-in-review',
    storyPoints: 5,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(1),
    sprintId: 'sprint-2',
    order: 1,
    inProgressAt: daysAgo(3),
    tags: ['frontend', 'agile'],
  },
  {
    id: 'task-7',
    title: 'Add sprint management',
    notes: 'Create, edit, and activate sprints; assign tasks to sprints from backlog',
    columnId: 'col-todo',
    storyPoints: 5,
    createdAt: daysAgo(11),
    updatedAt: daysAgo(11),
    sprintId: 'sprint-2',
    order: 2,
    dueDate: daysAhead(5),
    tags: ['frontend', 'sprints'],
  },
  {
    id: 'task-8',
    title: 'Multi-field search and filtering',
    notes: 'Search by title, description, status, story points, and dates with operators',
    columnId: 'col-todo',
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
    sprintId: 'sprint-2',
    order: 3,
    tags: ['frontend', 'search'],
  },
  {
    id: 'task-9',
    title: 'Done folder and trash bin',
    notes: 'Archive completed tasks and soft-delete with 30-day retention period',
    columnId: 'col-done',
    storyPoints: 3,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(4),
    sprintId: 'sprint-2',
    order: 4,
    inProgressAt: daysAgo(8),
    dueDate: daysAhead(1),
    tags: ['frontend'],
  },
  {
    id: 'task-10',
    title: 'Keyboard shortcuts',
    notes: 'Implement / and Cmd-F for search focus, Esc to clear',
    columnId: 'col-todo',
    storyPoints: 2,
    createdAt: daysAgo(9),
    updatedAt: daysAgo(9),
    sprintId: 'sprint-2',
    order: 5,
    tags: ['frontend', 'ux'],
  },

  // Sprint 3 – future sprint, all not started
  {
    id: 'task-11',
    title: 'Mobile responsive design',
    notes: 'Optimize all views for tablet and mobile screen sizes',
    columnId: 'col-todo',
    storyPoints: 5,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
    sprintId: 'sprint-3',
    order: 0,
    dueDate: daysAhead(10),
    tags: ['frontend', 'mobile'],
  },
  {
    id: 'task-12',
    title: 'Dark mode support',
    notes: 'Implement theme switching with system preference detection',
    columnId: 'col-todo',
    storyPoints: 3,
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
    sprintId: 'sprint-3',
    order: 1,
    tags: ['frontend', 'ux'],
  },
  {
    id: 'task-13',
    title: 'Export to CSV',
    notes: 'Allow users to export task lists and sprint reports as CSV files',
    columnId: 'col-todo',
    storyPoints: 2,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
    sprintId: 'sprint-3',
    order: 2,
    dueDate: daysAhead(12),
    tags: ['feature'],
    predecessorIds: ['task-9'],
  },

  // Backlog tasks (no sprint)
  {
    id: 'task-14',
    title: 'Email notification system',
    notes: 'Send digest emails for sprint summaries and overdue task reminders',
    columnId: 'col-todo',
    storyPoints: 13,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(20),
    order: 0,
    tags: ['backend', 'notifications'],
  },
  {
    id: 'task-15',
    title: 'Slack integration',
    notes: 'Post notifications to Slack channels when tasks move to done or get assigned',
    columnId: 'col-todo',
    createdAt: daysAgo(18),
    updatedAt: daysAgo(18),
    order: 1,
    dueDate: daysAhead(30),
    tags: ['integration'],
  },
  {
    id: 'task-16',
    title: 'Analytics dashboard',
    notes: 'Velocity charts, burndown graphs, and team performance metrics',
    columnId: 'col-todo',
    storyPoints: 21,
    createdAt: daysAgo(15),
    updatedAt: daysAgo(15),
    order: 2,
    tags: ['feature', 'analytics'],
    predecessorIds: ['task-9'],
  },

  // Trash items
  {
    id: 'task-17',
    title: 'Old API v1 documentation',
    notes: 'Documentation for the deprecated v1 API endpoints – no longer needed',
    columnId: 'col-todo',
    createdAt: daysAgo(30),
    updatedAt: daysAgo(5),
    order: 99,
    deletedAt: daysAgo(5),
    tags: ['docs'],
  },
  {
    id: 'task-18',
    title: 'Duplicate: Setup CI pipeline',
    notes: 'This was a duplicate of task-1 and was removed',
    columnId: 'col-todo',
    storyPoints: 1,
    createdAt: daysAgo(35),
    updatedAt: daysAgo(29),
    order: 100,
    deletedAt: daysAgo(29),
    tags: ['infrastructure'],
  },
];
